ItineraryCollab/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'admin/login.html'}, name="login"),
    url(r'^accounts/logout/$', auth_views.logout_then_login, name="logout"),
    url(r'^', include('triplan.urls', namespace="triplan")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

triplan/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from triplan import views

urlpatterns = [
    url(r'^$', login_required(views.HomepageView.as_view()),
        name="itinerary_list"),
    url(r'^search/(?P<search_str>[+\w{}.-]{0,40})/$', login_required(views.ItineraryListByLocationView.as_view()),
        name='itinerary_list_search'),
    url(r'^category/(?P<category_pk>[0-9]+)/$', login_required(views.ItineraryListByCategory.as_view()),
        name="itinerary_list_category"),
    url(r'^create/$', login_required(views.ItineraryCreate.as_view()),
        name="itinerary_create"),
    url(r'^(?P<pk>[0-9]+)/create/$', login_required(views.ItinerarySegmentCreate.as_view()),
        name="itinerarysegment_create"),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.ItineraryDetailView.as_view()),
        name="itinerary_detail"),
    url(r'^(?P<pk>[0-9]+)/addreview/$', login_required(views.ReviewCreate.as_view()),
        name="review_create"),
    url(r'^(?P<pk>[0-9]+)/edit/$', login_required(views.ItineraryEdit.as_view()),
        name="itinerary_edit"),
    url(r'^(?P<itinerary_pk>[0-9]+)/(?P<pk>[0-9]+)/edit/$', login_required(views.ItinerarySegmentEdit.as_view()),
        name="itinerarysegment_edit"),
    url(r'my_profile/$', login_required(views.UserProfile.as_view()),
        name="user_profile"),
]

triplan/models.py
from datetime import datetime, date, timedelta
import urllib

from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=300)

    def __str__(self):
        return self.user.username


class Itinerary(models.Model):
    title = models.CharField(max_length=50)
    owner = models.ForeignKey(Profile, related_name='owner', on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now=True)
    preview_photo = models.ImageField(blank=True)
    shared_users = models.ManyToManyField(Profile, related_name='shared_users', blank=True)
    public_view = models.BooleanField(default=True)
    favourited_by = models.ManyToManyField(Profile, related_name='fav_by', blank=True)

    def __str__(self):
        return self.title

    @property
    def encoded_locations(self):
        location_list = []
        for segment in self.itinerarysegment_set.all():
            location_list.append(urllib.parse.quote_plus(segment.location))
        return "%7C".join(location_list)

    @property
    def total_duration(self):
        days = 1
        for segment in self.itinerarysegment_set.all():
            if segment.day_number > days:
                days = segment.day_number
        return days

    @property
    def total_duration_str(self):
        return self.total_duration
        # return self.format_delta_time(self.total_duration)

    @property
    def total_cost(self):
        cost = 0
        for segment in self.itinerarysegment_set.all():
            cost += segment.cost
        return cost

    @staticmethod
    def format_delta_time(tdelta):
        res = ""
        days = tdelta.days
        hours, rem = divmod(tdelta.seconds, 3600)
        minutes, sec = divmod(rem, 60)
        if days > 0:
            res += str(days) + "days "
        if hours > 0:
            res += str(hours) + "h "
        if minutes > 0:
            res += str(minutes) + "min"
        if res == "":
            return "No trips added"
        return res


class CategoryUtil:
    category_list = ["Food", "Educational", "Outdoor", "Games", "Social", "Shopping",
                     "Casino", "Recreational", "Photo-spot", "Transport", "Flight", "Other"]
    icon_list     = ["cutlery", "university", "sun-o", "gamepad", "users", "shopping-bag",
                     "money", "soccer-ball-o", "camera", "subway", "plane", "lightbulb-o"]

    @staticmethod
    def get_category_names():
        return CategoryUtil.category_list

    @staticmethod
    def get_category_choices():
        integer_list = list(range(0, len(CategoryUtil.category_list)))
        return zip(integer_list, CategoryUtil.category_list)

    @staticmethod
    def prepend_class_name(icon_name):
        return "fa fa-lg fa-" + str(icon_name)

    @staticmethod
    def get_icon_class(category):
        icon_class_name_list = map(CategoryUtil.prepend_class_name, CategoryUtil.icon_list)
        return (
            dict(zip(list(range(0, len(CategoryUtil.category_list))), icon_class_name_list))
        ).get(category, "")


class ItinerarySegment(models.Model):
    itinerary = models.ForeignKey(Itinerary)
    location = models.CharField(max_length=200)
    day_number = models.PositiveIntegerField(default=1)
    start_time = models.TimeField(default="12:00 PM")
    end_time = models.TimeField(default="1:00 PM")
    description = models.CharField(max_length=400)
    photo = models.ImageField(blank=True)
    category = models.IntegerField(default=0, choices=CategoryUtil.get_category_choices())
    cost = models.DecimalField(default=0, decimal_places=2, max_digits=6)

    class Meta:
        ordering = ['day_number', 'start_time']

    def __str__(self):
        return self.itinerary.__str__() + self.description.__str__()

    @property
    def duration(self):
        # assume duration always < 1 day
        # TODO: display in hours and minutes / smart display
        return datetime.combine(date.today(), self.end_time) - datetime.combine(date.today(), self.start_time)

    @property
    def encoded_location(self):
        return urllib.parse.quote_plus(self.location)

    @property
    def category_icon_class(self):
        return CategoryUtil.get_icon_class(self.category)


class Review(models.Model):
    itinerary = models.ForeignKey(Itinerary)
    reviewer = models.ForeignKey(Profile)
    rating = models.PositiveIntegerField()
    comment = models.CharField(max_length=200)
    reviewed_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-reviewed_at']

triplan/views.py
import urllib

from django import forms
from django.db.models import Q
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView
from django.views.generic.list import MultipleObjectMixin

from triplan.models import Itinerary, ItinerarySegment, Profile, CategoryUtil, Review


class HomepageView(View):
    def get(self, request, *args, **kwargs):
        view = ItineraryList.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = LocationSearch.as_view()
        return view(request, *args, **kwargs)


class LocationSearchForm(forms.Form):
    search_str = forms.CharField()


class LocationSearch(MultipleObjectMixin, FormView):
    template_name = "triplan/itinerary_list.html"
    form_class = LocationSearchForm

    def __init__(self):
        super().__init__()
        self.object_list = []

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        return super(LocationSearch, self).post(request, *args, **kwargs)

    def get_success_url(self):
        form = self.get_form()
        search_str = urllib.parse.quote_plus(form.data['search_str'])
        return reverse_lazy('triplan:itinerary_list_search', kwargs={'search_str': search_str})


class ItineraryList(generic.ListView):
    def get_context_data(self, **kwargs):
        context = super(ItineraryList, self).get_context_data(**kwargs)
        context['title'] = "Ready for your next trip " + self.request.user.username + "?"
        context['category'] = 'All'
        context['all_categories'] = CategoryUtil.get_category_names()
        context['form'] = LocationSearchForm()
        return context

    def get_queryset(self):
        return Itinerary.objects.all().order_by("-date_added")


class ItineraryListByLocationView(View):
    def get(self, request, *args, **kwargs):
        view = ItineraryListByLocation.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = LocationSearch.as_view()
        return view(request, *args, **kwargs)


class ItineraryListByLocation(generic.ListView):
    def get_context_data(self, **kwargs):
        context = super(ItineraryListByLocation, self).get_context_data(**kwargs)
        context['category'] = 'All'
        context['all_categories'] = CategoryUtil.get_category_names()
        context['search_str'] = self.kwargs['search_str']
        context['form'] = LocationSearchForm()
        context['search_text'] = ' for "' + self.parsed_search_str + '"'
        return context

    def get_queryset(self):
        self.parsed_search_str = urllib.parse.unquote_plus(self.kwargs['search_str'])
        return Itinerary.objects.filter(title__contains=self.parsed_search_str)


class ItineraryListByCategory(generic.ListView):
    def get_queryset(self):
        return Itinerary.objects.all()\
            .filter(itinerarysegment__category=self.kwargs['category_pk'])\
            .order_by("-date_added")

    def get_context_data(self, **kwargs):
        context = super(ItineraryListByCategory, self).get_context_data(**kwargs)
        category_id = int(self.kwargs['category_pk'])
        context['category'] = CategoryUtil.get_category_names()[category_id]
        context['all_categories'] = CategoryUtil.get_category_names()
        context['search_text'] = ' under "' + context['category'] + '" category'
        return context


class ItineraryDetailView(View):
    def get(self, request, *args, **kwargs):
        view = ItineraryDetail.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = Favourite.as_view()
        return view(request, *args, **kwargs)


class ItineraryDetail(generic.DetailView):
    model = Itinerary

    def get_context_data(self, **kwargs):
        context = super(ItineraryDetail, self).get_context_data(**kwargs)
        itinerary = Itinerary.objects.get(id=self.kwargs['pk'])
        curr_user_id = self.request.user.id
        context['is_owner'] = itinerary.owner_id == curr_user_id
        context['form'] = FavouriteForm(initial={'fav': itinerary.favourited_by.filter(id=curr_user_id).exists()})
        return context

    def days_range(self):
        return range(1, self.get_object().total_duration + 1)

    def get_queryset(self):
        return Itinerary.objects.filter(Q(owner__user=self.request.user) |
                                        Q(shared_users__user=self.request.user) |
                                        Q(public_view=True)
                                        ).distinct()


class FavouriteForm(forms.Form):
    fav = forms.BooleanField(widget=forms.CheckboxInput(attrs={'onclick': 'this.form.submit();'}),
                             label="I like this!")


class Favourite(SingleObjectMixin, FormView):
    template_name = 'triplan/itinerary_detail.html'
    success_url = reverse_lazy('triplan:itinerary_detail')
    model = Itinerary

    def get_form(self, **kwargs):
        return FavouriteForm(initial={'fav': Itinerary.objects.get(id=self.kwargs['pk']).favourited_by.filter(id=self.request.user.id).exists()})

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super(Favourite, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        success_url = super(Favourite, self).form_valid(form)
        profile = Profile.objects.get(id=self.request.user.id)
        itinerary = Itinerary.objects.get(id=self.kwargs['pk'])
        # if form.instance.fav:
        #     itinerary.favourited_by.add(profile)
        # else:
        itinerary.favourited_by.remove(profile)
        itinerary.save()
        return success_url


class ItineraryCreate(generic.edit.CreateView):
    model = Itinerary
    fields = ['public_view', 'public_view', 'shared_users', 'title', 'preview_photo']
    success_url = reverse_lazy('triplan:itinerary_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user.profile
        form.instance.save()
        return super(ItineraryCreate, self).form_valid(form)

    def get_form(self):
        form = super(ItineraryCreate, self).get_form()
        form.fields['shared_users'].queryset = Profile.objects.exclude(
            user=self.request.user)
        return form


class ItinerarySegmentCreate(generic.edit.CreateView):
    model = ItinerarySegment
    fields = ['photo', 'location', 'category', 'description', 'day_number', 'start_time', 'end_time', 'cost']
    widgets = {
        # "start_time": AdminTimeWidget(format='fa'),
        # "end_time": AdminTimeWidget(format='fa'),
        'start_time': forms.TimeInput(format='%H:%M %p'),
        'end_time': forms.TimeInput(format='%H:%M %p'),
    }

    def get_context_data(self, **kwargs):
        context = super(ItinerarySegmentCreate, self).get_context_data(**kwargs)
        context['itinerary'] = Itinerary.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.itinerary = Itinerary.objects.get(id=self.kwargs['pk'])
        form.instance.save()
        return super(ItinerarySegmentCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('triplan:itinerary_detail', args=[self.kwargs['pk']])


class ItineraryEdit(generic.edit.UpdateView):
    template_name = "triplan/itinerary_edit.html"
    model = Itinerary
    fields = ['title', 'public_view', 'shared_users', 'preview_photo']
    success_url = reverse_lazy('triplan:itinerary_list')

    def get_form(self):
        form = super(ItineraryEdit, self).get_form()
        form.fields['shared_users'].queryset = Profile.objects.exclude(
            user=self.request.user)
        return form

class ItinerarySegmentEdit(generic.edit.UpdateView):
    template_name = 'triplan/itinerarysegment_edit.html'
    model = ItinerarySegment
    fields = ['photo', 'location', 'category', 'description', 'day_number', 'start_time', 'end_time', 'cost']
    widgets = {
        'start_time': forms.TimeInput(format='fa'),
        'end_time': forms.TimeInput(format='fa'),
    }

    def get_success_url(self):
        return reverse_lazy('triplan:itinerary_detail', args=[self.kwargs['itinerary_pk']])


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']


class ReviewCreate(generic.edit.CreateView):
    template_name = 'triplan/review_form.html'
    form = ReviewForm()
    fields = form.fields
    model = Review

    def get_context_data(self, **kwargs):
        context = super(ReviewCreate, self).get_context_data()
        context['itinerary'] = Itinerary.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.itinerary = Itinerary.objects.get(id=self.kwargs['pk'])
        form.instance.reviewer = self.request.user.profile
        form.instance.save()
        return super(ReviewCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('triplan:itinerary_detail', args=[self.kwargs['pk']])


class UserProfile(generic.list.ListView):
    template_name = 'triplan/itinerary_list.html'

    def get_context_data(self, **kwargs):
        context = super(UserProfile, self).get_context_data(**kwargs)
        context['title'] = "Hi " + self.request.user.username + ", here are the itineraries owned by you"
        context['category'] = 'All'
        context['all_categories'] = CategoryUtil.get_category_names()
        context['form'] = LocationSearchForm()
        return context

    def get_queryset(self):

triplan/templates/triplan/edit_form.html
{% load bootstrap3 %}

<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% bootstrap_alert form.non_field_errors %}
    {% endif %}

    {% for field in form %}
        {% bootstrap_field field layout='horizontal' horizontal_field_class='padding-tb-5 col-md-10' horizontal_label_class='form-label-align col-md-2'%}
    {% endfor %}

    <div class="col-sm-12">
        <a href="{{ back_url }}" class="btn btn-default">Back</a>
        <button class="btn btn-success pull-right" type="submit">Save</button>
    </div>
</form>

triplan/templates/triplan/itinerary_detail.html
{% extends "triplan/base.html" %}

{% block imports %}
    {% load static %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{% static 'shared_users_select2.js'%}"></script>

    <script src="{% static 'itinerary_detail.js' %}"></script>
{% endblock imports %}

{% block body %}
{% load humanize %}
{% load mathfilters %}

<div class="col-sm-10 col-sm-offset-1">
    <div class="col-sm-12">
        <h2 class="center">{{ itinerary.title }}</h2>
        <p><small class="pull-right margin-bottom-5">added by {{ itinerary.owner }} on {{ itinerary.date_added|naturaltime }}</small></p>
    </div>

{#  Mark as Favourite  #}
{#    <form method="post">#}
{#        <label>#}
{#            {% csrf_token %}#}
{#            {{ form }}#}
{#            <i class="fa fa-heart fa-2x boolean-true"></i>#}
{#            <i class="fa fa-heart-o fa-2x boolean-false"></i>#}
{#        </label>#}
{#    </form>#}
    <h5>Favourited by {{ itinerary.favourited_by.all|length }} user{{ itinerary.favourited_by.all|length|pluralize }}</h5>
    {% for u in itinerary.favourited_by.all %}
        {{ u }} &nbsp;
    {% endfor %}
    <div class="col-sm-12 margin-5">
        {% if itinerary.preview_photo %}
        <img src="{{ itinerary.preview_photo.url }}" class="img img-responsive full-width center-img">
        {% endif %}
    </div>

    {% if is_owner %}
    <a href="{% url 'triplan:itinerary_edit' itinerary.id %}" class="btn btn-success pull-right">
        Edit Itinerary
    </a>
    {% endif %}

    {# Static Map #}
    {# https://developers.google.com/maps/documentation/static-maps/intro #}
    <div class="col-sm-12 margin-5">
        <button id="map-zoom" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
        <img id="default-map" src=
         "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap\&markers=size:mid%7Ccolor:red%7C{{ itinerary.encoded_locations }}&key=AIzaSyBJz1pSa-my6Cq3DrqIy-MB0keiTHL-rq8"
            width="600px" height="300px" class="img center-img">
        <img id="zoomed-map" src=
         "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap\&markers=size:mid%7Ccolor:red%7C{{ itinerary.encoded_locations }}&key=AIzaSyBJz1pSa-my6Cq3DrqIy-MB0keiTHL-rq8&zoom=12"
            width="600px" height="300px" class="img center-img hide">
    </div>

    {# Itinerary Segment #}
    <div class="col-sm-12 margin-top-20">
        {% if itinerary.itinerarysegment_set.all|length_is:"0" %}
            <p class="center">{{ itinerary.owner }} has not added any destinations yet :(</p>
        {% else %}

            {% for segment in itinerary.itinerarysegment_set.all %}
            <div class="segment-wrapper">
                {# Timeline #}
                <div class="col-sm-1 timings">
                    <p class="day">Day {{ segment.day_number }}</p>
                    <p class="start-time badge">{{ segment.start_time }}</p>
                    <p class="end-time badge">{{ segment.end_time }}</p>
                </div>

                {# Info #}
                <div class="col-sm-5 col-xs-12 itinerary-seg">
                    <h4><span id="cateogy-icon" class="{{ segment.category_icon_class }}" area-hidden="true"></span>
                        {{ segment.get_category_display }}</h4>
                    <p><strong>Location:</strong> {{ segment.location }}</p>
                    <p><strong>Duration:</strong> {{ segment.duration }}h</p>
                    <p>Cost:
                        {% if segment.cost == 0 %}
                            FREE
                        {% else %}
                        £{{ segment.cost|floatformat:2|intcomma}}
                        {% endif %}
                    </p>
                    <p><strong>Description:</strong> {{ segment.description }}</p>
                </div>

                {# Images #}
                <div class="col-sm-5 col-xs-10">
                    <img id="default-map" src=
                    "https://maps.googleapis.com/maps/api/staticmap?size=200x150&maptype=roadmap\&markers=size:mid%7Ccolor:red%7C{{ segment.encoded_location }}&key=AIzaSyBJz1pSa-my6Cq3DrqIy-MB0keiTHL-rq8&zoom=15"
                     class="img center-img img-responsive full-width margin-5">
                    {% if segment.photo %}
                        <img src="{{ segment.photo.url }}" class="img img-responsive full-width margin-5">
                    {% endif %}
                </div>

                {# Edit button #}
                <div class="col-sm-1 col-xs-2">
                {% if itinerary.owner_id == request.user.id %}
                    <a href="{% url 'triplan:itinerarysegment_edit' itinerary.id segment.id %}"
                       class="btn btn-info pull-right">Edit</a>
                {% endif %}
                </div>

            </div>
            {% endfor %}
        </div>

        {# Total cost #}
        <div class="col-sm-12 total-cost">
            <hr>
            <h3 class="pull-left">
                <span class="fa fa-calculator fa-lg"></span>
                Total cost = £{{ itinerary.total_cost }}
            </h3>
        </div>
    {% endif %}

    {# Owner Buttons #}
    {% if is_owner %}
    <div class="col-sm-12">
        <a href="{% url 'triplan:itinerary_list' %}" class="btn btn-default">Back</a>
        <a href="{% url 'triplan:itinerarysegment_create' itinerary.id %}" class="btn btn-success pull-right">Add New Segment</a>
    </div>
    {% endif %}
</div>


{#  Reviews  #}
{% if not is_owner %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="col-sm-12">
        <h3 class="pull-left">Reviews ({{ itinerary.review_set.all|length }})</h3>
        <a href="{% url 'triplan:review_create' itinerary.id %}" class="btn btn-success pull-right">Been here? Add a review</a>
    </div>
    <div class="col-sm-12">
        <ul class="list-group">
        {% for review in itinerary.review_set.all %}
            <li class="list-group-item">
                <small class="pull-right">{{ review.reviewed_at|naturaltime }}</small>
                <p>{{ review.reviewer }} rated {{ review.rating }}/10</p>
                <p>"{{ review.comment }}"</p>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endif %}

<br>
{#  Calendar  #}
<div class="col-sm-8 col-sm-offset-2 calendar">
<h3>Calendar view &nbsp;<span class="fa fa-lg fa-calendar"></span></h3>

{% for day in view.days_range %}
    <div class="col-sm-3">
        <h4>Day {{ day }}</h4>
        {% for segment in itinerary.itinerarysegment_set.all %}
            {% if segment.day_number == day %}
            <div class="alert alert-success" style="padding-bottom: {{ segment.duration.seconds|div:36|div:24|mul:2 }}%">
                <p>{{ segment.location|truncatewords:5 }}</p>
                <p>{{ segment.start_time }} - {{ segment.end_time }}</p>
            </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}
</div>

{% endblock body %}

triplan/templates/triplan/itinerary_edit.html
{% extends 'triplan/base.html' %}

{% block imports %}
    {% load static %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{% static 'shared_users_select2.js'%}"></script>
{% endblock imports %}

{% block body %}

<div class="col-sm-8 col-sm-offset-2">
    <h3>Editing <strong>{{ itinerary.title }}</strong></h3>
    {% if itinerary.preview_photo %}
    <img src="{{ itinerary.preview_photo.url }}" class="img img-responsive center-img full-width">
    {% endif %}

    {% url 'triplan:itinerary_list' as url %}
    {% include 'triplan/edit_form.html' with back_url=url %}

</div>

{% endblock body %}

triplan/templates/triplan/itinerary_form.html
{% extends 'triplan/base.html' %}
{% block body %}
{% load bootstrap3 %}

<div class="panel col-sm-8 col-sm-offset-2">
    <h3>Create new itinerary</h3>
    {% url 'triplan:itinerary_list' as url %}
    {% include 'triplan/edit_form.html' with back_url=url %}
</div>

{% endblock body %}

triplan/templates/triplan/itinerary_list.html
{% extends "triplan/base.html" %}

{% block body %}
{% load humanize %}

<div class="panel col-sm-10 col-sm-offset-1">
    <div class="col-sm-12 margin-5">
        <h1> {{ title }} </h1>
        <a href="{% url 'triplan:itinerary_create' %}" class="btn btn-success pull-right">Create new itinerary</a>

    {#  Category dropdown menu  #}
        <ul class="dropdown-menu" role="group">
            <li><a href="{% url 'triplan:itinerary_list' %}">All</a></li>
            {% for c in all_categories %}
                <li><a href="{% url 'triplan:itinerary_list_category' forloop.counter0 %}">{{ c }}</a></li>
            {% endfor %}
        </ul>

    {#  Category filter  #}
        <button type="button" class="btn btn-default dropdown-toggle pull-left" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ category }}
            <span class="caret"></span>
        </button>

    </div>

    <div class="col-sm-12">
    {#   Itinerary search text   #}
        <small class="col-sm-12">{{ itinerary_list|length }} itinerar{{ itinerary_list|length|pluralize:"y,ies" }} found {{ search_text }}</small>

        {% for itinerary in itinerary_list %}
        <div class="col-sm-4 col-xs-6">
            <a href="{% url 'triplan:itinerary_detail' itinerary.id %}">
                <div class="itinerary-preview margin-5">
            {#  Preview photo   #}
                    {% if itinerary.preview_photo %}
                    <img src="{{ itinerary.preview_photo.url }}" class="img img-responsive full-width">
                    {% else %}
                    <img src="http://misshighpoint.com/uploads/6/3/2/1/63216997/square-placeholder_1_orig.jpg"
                         class="img img-responsive full-width">
                    {% endif %}
            {#  Overlayed Description  #}
                    <p class="itinerary-desc">
                        <strong class="itinerary-text">{{ itinerary.title }} </strong><br/>
                        <span class="itinerary-text">
                            {{ itinerary.total_duration_str }} days,&nbsp;£{{ itinerary.total_cost }}
                        </span>
                    </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock body %}

triplan/templates/triplan/review_form.html
{% extends "triplan/base.html" %}

{% block body %}
    <div class="col-sm-6 col-sm-offset-3">
        <h3>Add review for {{ itinerary.title }}:</h3>
        {% url 'triplan:itinerary_detail' itinerary.id as url %}
        {% include 'triplan/edit_form.html' with back_url=url %}
    </div>
{% endblock body %}